// Generated by https://quicktype.io

export interface GetResponseEmployees {
  success: boolean;
  data: Data;
}

export interface Data {
  employees: Employee[];
}

export interface Employee {
  id: number;
  name: string;
  last_name: string;
  birthday: number;
}

export interface ArgEmployeesApi {
  name: string;
  last_name: string;
  birthday: string;
}
